### ISSUE TITLE
Euclidean misbehaving

### ISSUE THREAD

**Issue by mortonjt** [qiime2/q2-diversity#213]
**Bug Description**
Something wonky is going on with the Euclidean distance calculations

Below is the error message

```
Traceback (most recent call last):
  File "/Users/mortonjt/miniconda3/envs/qiime2-2018.6/lib/python3.5/site-packages/q2cli/commands.py", line 274, in __call__
    results = action(**arguments)
  File "<decorator-gen-354>", line 2, in beta
  File "/Users/mortonjt/miniconda3/envs/qiime2-2018.6/lib/python3.5/site-packages/qiime2/sdk/action.py", line 232, in bound_callable
    output_types, provenance)
  File "/Users/mortonjt/miniconda3/envs/qiime2-2018.6/lib/python3.5/site-packages/qiime2/sdk/action.py", line 367, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/Users/mortonjt/Dropbox/UCSD/research/software/q2/q2-diversity/q2_diversity/_beta/_method.py", line 142, in beta
    n_jobs=n_jobs
  File "/Users/mortonjt/Dropbox/UCSD/research/software/scikit-bio/skbio/diversity/_driver.py", line 381, in beta_diversity
    return DistanceMatrix(distances, ids)
  File "/Users/mortonjt/Dropbox/UCSD/research/software/scikit-bio/skbio/stats/distance/_base.py", line 106, in __init__
    self._validate(data, ids)
  File "/Users/mortonjt/Dropbox/UCSD/research/software/scikit-bio/skbio/stats/distance/_base.py", line 873, in _validate
    "Data must be symmetric and cannot contain NaNs.")
skbio.stats.distance._base.DistanceMatrixError: Data must be symmetric and cannot contain NaNs.
```

**Comments**
There are a couple of things to note
1. No errors are thrown when performing Bray-Curtis or Aitchison distance in #208 
2. This is using the relaxed type checking in https://github.com/biocore/scikit-bio/pull/1583

Not completely sure of the cause -- I'm just raising this here so that we don't forget this.

**Comment by cherman2** [comment]
I think this was fixed by #208. Closing Issue, Please reopen if I am mistaken!
